### ISSUE TITLE
Missing 'off' as a thermostatMode

### ISSUE THREAD

**Issue by jcox10** [tomwpublic/hubitat_midea#5]
In 0.9.1 `off` was a thermostat mode. It is now missing in 0.9.3. This make it so the AC cannot be turned off from a dashboard `thermostat` tile.

**Comment by tomwpublic** [comment]
Does it fix the issue if you add "off" to the list of thermostat modes at line ~121?

**Comment by jcox10** [comment]
Adding it to the list works, just had to move the conditional in `setThermostatMode` to catch the `off` command first. I created a PR with the changes.

**Comment by tomwpublic** [comment]
Merged in your changes as v0.9.4.  Thanks for the bugfix!
